#!/usr/bin/env nextflow
// Generated by Mendel. Do not edit by hand — edit the goal and recompile.
//
// Mendel constructs and documents analysis pipelines. It is not a diagnostic
// device and produces no diagnostic result. This pipeline must be validated by
// the laboratory before clinical use.
nextflow.enable.dsl = 2

include { TRIMGALORE } from './modules/nf-core/trimgalore/main'
include { STAR_ALIGN } from './modules/nf-core/star/align/main'

// tier 2 (none): contract default
params.star_align_seq_platform = 'illumina'

workflow {
    ch_reads = Channel.fromFilePairs(params.input, checkIfExists: true).map { id, reads -> [ [id: id], reads ] }
    ch_star = Channel.fromPath(params.star, checkIfExists: true).map { f -> [ [:], f ] }

    TRIMGALORE(ch_reads)
    STAR_ALIGN(TRIMGALORE.out.reads, ch_star, Channel.value([[:], []]), false)
}
