"""wiener: run, run_event, run_task, run_artifact

Revision ID: 7c7286bda2b0
Revises: 
Create Date: 2026-08-24 12:00:15.872894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7286bda2b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lab_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('submitted_by', sa.String(length=200), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('executor', sa.String(length=16), nullable=False),
    sa.Column('ingest_secret', sa.String(length=64), nullable=False),
    sa.Column('nextflow_run_name', sa.String(length=120), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_artifact_id'), 'run', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_run_lab_id'), 'run', ['lab_id'], unique=False)
    op.create_index(op.f('ix_run_phase'), 'run', ['phase'], unique=False)
    op.create_index(op.f('ix_run_submitted_at'), 'run', ['submitted_at'], unique=False)
    op.create_table('run_artifact',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lab_id', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', sa.String(length=200), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('digest', sa.String(length=71), nullable=False),
    sa.Column('pipeline_digest', sa.String(length=71), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_artifact_lab_id'), 'run_artifact', ['lab_id'], unique=False)
    op.create_table('run_event',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('lab_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('at_ms', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'seq')
    )
    op.create_index(op.f('ix_run_event_lab_id'), 'run_event', ['lab_id'], unique=False)
    op.create_table('run_task',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('lab_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('process', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.JSON(), nullable=False),
    sa.Column('latest_exit', sa.Integer(), nullable=True),
    sa.Column('last_change_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'task_id')
    )
    op.create_index(op.f('ix_run_task_lab_id'), 'run_task', ['lab_id'], unique=False)
    op.create_index(op.f('ix_run_task_process'), 'run_task', ['process'], unique=False)
    op.create_index(op.f('ix_run_task_status'), 'run_task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_task_status'), table_name='run_task')
    op.drop_index(op.f('ix_run_task_process'), table_name='run_task')
    op.drop_index(op.f('ix_run_task_lab_id'), table_name='run_task')
    op.drop_table('run_task')
    op.drop_index(op.f('ix_run_event_lab_id'), table_name='run_event')
    op.drop_table('run_event')
    op.drop_index(op.f('ix_run_artifact_lab_id'), table_name='run_artifact')
    op.drop_table('run_artifact')
    op.drop_index(op.f('ix_run_submitted_at'), table_name='run')
    op.drop_index(op.f('ix_run_phase'), table_name='run')
    op.drop_index(op.f('ix_run_lab_id'), table_name='run')
    op.drop_index(op.f('ix_run_artifact_id'), table_name='run')
    op.drop_table('run')
    # ### end Alembic commands ###
