"""gate_run

Revision ID: 00b5047c9d2f
Revises: b6e3e0e31b73
Create Date: 2026-08-23 20:00:36.738080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b5047c9d2f'
down_revision: Union[str, Sequence[str], None] = 'b6e3e0e31b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('who', sa.String(length=200), nullable=False),
    sa.Column('gate', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_run_draft_id'), 'gate_run', ['draft_id'], unique=False)
    op.create_index(op.f('ix_gate_run_queued_at'), 'gate_run', ['queued_at'], unique=False)
    op.create_index(op.f('ix_gate_run_state'), 'gate_run', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_run_state'), table_name='gate_run')
    op.drop_index(op.f('ix_gate_run_queued_at'), table_name='gate_run')
    op.drop_index(op.f('ix_gate_run_draft_id'), table_name='gate_run')
    op.drop_table('gate_run')
    # ### end Alembic commands ###
