"""forge workflow

Seven tables for the forge's durable workflow. Written by hand rather than autogenerated:
autogenerate needs a live database, and the partial unique index below is the one thing it
would have got wrong anyway — `postgresql_where` survives a round trip through the model
metadata, but a reviewer reading a generated file cannot tell a deliberate partial index from
a comparison artefact.

**Every foreign key is RESTRICT.** Archiving an adaptation never deletes its revisions, events,
messages or invocation audit, and the way that rule stays true is that there is no cascade to
break it with.

Revision ID: a1f4c7d20e93
Revises: 00b5047c9d2f
Create Date: 2026-09-04

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1f4c7d20e93"
down_revision: Union[str, Sequence[str], None] = "00b5047c9d2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "forge_source_snapshot",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_revision", sa.String(length=200), nullable=False),
        sa.Column("etag", sa.String(length=200), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("last_successful_sync_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forge_source_snapshot_source"), "forge_source_snapshot", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_forge_source_snapshot_started_at"),
        "forge_source_snapshot",
        ["started_at"],
        unique=False,
    )
    op.create_index(op.f("ix_forge_source_snapshot_ok"), "forge_source_snapshot", ["ok"])

    op.create_table(
        "forge_catalogue_item",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("ref", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("adaptable", sa.Boolean(), nullable=False),
        sa.Column("unsupported_reason", sa.Text(), nullable=False),
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["forge_source_snapshot.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_forge_catalogue_item_source_ref",
        "forge_catalogue_item",
        ["source", "ref"],
        unique=True,
    )
    for column in ("snapshot_id", "source", "ref", "content_digest", "adaptable", "present"):
        op.create_index(
            op.f(f"ix_forge_catalogue_item_{column}"), "forge_catalogue_item", [column]
        )
    op.create_index(
        op.f("ix_forge_catalogue_item_last_seen_at"), "forge_catalogue_item", ["last_seen_at"]
    )

    op.create_table(
        "forge_adaptation",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("catalogue_item_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("failed_stage", sa.String(length=24), nullable=True),
        sa.Column("current_revision_id", sa.String(length=32), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("registry_digest", sa.String(length=64), nullable=False),
        sa.Column("who", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalogue_item_id"], ["forge_catalogue_item.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    for column in ("catalogue_item_id", "state", "who", "created_at", "updated_at"):
        op.create_index(op.f(f"ix_forge_adaptation_{column}"), "forge_adaptation", [column])
    op.create_index(
        "ix_forge_adaptation_one_active",
        "forge_adaptation",
        ["catalogue_item_id"],
        unique=True,
        postgresql_where=sa.text("state NOT IN ('published', 'archived')"),
    )

    op.create_table(
        "forge_revision",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("adaptation_id", sa.String(length=32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.String(length=32), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("validation", sa.JSON(), nullable=False),
        sa.Column("green", sa.Boolean(), nullable=False),
        sa.Column("unresolved_required", sa.Integer(), nullable=False),
        sa.Column("prompt_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["adaptation_id"], ["forge_adaptation.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["parent_revision_id"], ["forge_revision.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_forge_revision_adaptation_ordinal",
        "forge_revision",
        ["adaptation_id", "ordinal"],
        unique=True,
    )
    for column in ("adaptation_id", "state", "green", "created_at"):
        op.create_index(op.f(f"ix_forge_revision_{column}"), "forge_revision", [column])

    op.create_table(
        "ai_invocation",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("prompt_id", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("prompt_digest", sa.String(length=64), nullable=False),
        sa.Column("input_digests", sa.JSON(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("failure_code", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    for column in ("agent", "purpose", "prompt_id", "state", "started_at"):
        op.create_index(op.f(f"ix_ai_invocation_{column}"), "ai_invocation", [column])

    op.create_table(
        "forge_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("adaptation_id", sa.String(length=32), nullable=False),
        sa.Column("revision_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["adaptation_id"], ["forge_adaptation.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["revision_id"], ["forge_revision.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    for column in ("adaptation_id", "revision_id", "kind", "at"):
        op.create_index(op.f(f"ix_forge_event_{column}"), "forge_event", [column])

    op.create_table(
        "forge_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("adaptation_id", sa.String(length=32), nullable=False),
        sa.Column("revision_id", sa.String(length=32), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("ai_invocation_id", sa.String(length=32), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["adaptation_id"], ["forge_adaptation.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["revision_id"], ["forge_revision.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["ai_invocation_id"], ["ai_invocation.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    for column in ("adaptation_id", "revision_id", "state", "at"):
        op.create_index(op.f(f"ix_forge_message_{column}"), "forge_message", [column])


def downgrade() -> None:
    """Downgrade schema.

    Dropped in reverse dependency order. A table with a RESTRICT foreign key pointing at it
    cannot be dropped first, and the failure is a constraint violation halfway through rather
    than a clean refusal — so the order is the schema's, not alphabetical.
    """
    op.drop_table("forge_message")
    op.drop_table("forge_event")
    op.drop_table("ai_invocation")
    op.drop_table("forge_revision")
    op.drop_table("forge_adaptation")
    op.drop_table("forge_catalogue_item")
    op.drop_table("forge_source_snapshot")
