"""pipeline_draft

Revision ID: b6e3e0e31b73
Revises: e2edbd098caf
Create Date: 2026-08-23 12:36:13.304354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e3e0e31b73'
down_revision: Union[str, Sequence[str], None] = 'e2edbd098caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_draft',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('who', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_draft_updated_at'), 'pipeline_draft', ['updated_at'], unique=False)
    op.create_index(op.f('ix_pipeline_draft_who'), 'pipeline_draft', ['who'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_draft_who'), table_name='pipeline_draft')
    op.drop_index(op.f('ix_pipeline_draft_updated_at'), table_name='pipeline_draft')
    op.drop_table('pipeline_draft')
    # ### end Alembic commands ###
