"""source_check

Revision ID: c24b54f53588
Revises: 
Create Date: 2026-08-18 14:48:45.772744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24b54f53588'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked', sa.Integer(), nullable=False),
    sa.Column('drifted', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_check_ran_at'), 'source_check', ['ran_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_check_ran_at'), table_name='source_check')
    op.drop_table('source_check')
    # ### end Alembic commands ###
