"""queue_visit

Revision ID: e2edbd098caf
Revises: c24b54f53588
Create Date: 2026-08-18 19:00:53.822948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2edbd098caf'
down_revision: Union[str, Sequence[str], None] = 'c24b54f53588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.String(length=200), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_visit_seen_at'), 'queue_visit', ['seen_at'], unique=False)
    op.create_index(op.f('ix_queue_visit_who'), 'queue_visit', ['who'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_visit_who'), table_name='queue_visit')
    op.drop_index(op.f('ix_queue_visit_seen_at'), table_name='queue_visit')
    op.drop_table('queue_visit')
    # ### end Alembic commands ###
