#!/usr/bin/env nextflow
// Generated by Mendel. Do not edit by hand — edit the goal and recompile.
//
// Mendel constructs and documents analysis pipelines. It is not a diagnostic
// device and produces no diagnostic result. This pipeline must be validated by
// the laboratory before clinical use.
nextflow.enable.dsl = 2

include { TRIMGALORE } from './modules/nf-core/trimgalore/main'
include { STAR_GENOMEGENERATE } from './modules/nf-core/star/genomegenerate/main'
include { STAR_ALIGN } from './modules/nf-core/star/align/main'
include { SAMTOOLS_SORT } from './modules/nf-core/samtools/sort/main'
include { SUBREAD_FEATURECOUNTS } from './modules/nf-core/subread/featurecounts/main'

workflow {
    ch_annotation_gtf = Channel.fromPath(params.gtf, checkIfExists: true).map { gtf -> [ [id: gtf.baseName], gtf ] }
    ch_fastq_reads = (( params.input instanceof List ? Channel.of([ [id: 'test'], params.input.collect { file(it, checkIfExists: true) } ]) : Channel.fromFilePairs(params.input, checkIfExists: true).map { id, reads -> [ [id: id], reads ] } )).map { meta, files -> [ meta + [single_end: false, strandedness: 'reverse'], files ] }
    ch_genome_fasta = Channel.fromPath(params.fasta, checkIfExists: true).map { f -> [ [id: f.baseName], f ] }

    TRIMGALORE(ch_fastq_reads)
    STAR_GENOMEGENERATE(ch_genome_fasta, ch_annotation_gtf)
    STAR_ALIGN(TRIMGALORE.out.reads, STAR_GENOMEGENERATE.out.index, ch_annotation_gtf, false)
    SAMTOOLS_SORT(STAR_ALIGN.out.bam, Channel.value([[:], [], []]), 'bai')
    SUBREAD_FEATURECOUNTS(SAMTOOLS_SORT.out.bam.combine(ch_annotation_gtf.map { it[1] }))
}
