/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is the service up
         * @description Liveness only. What the *registry* looks like is `/health/registry`, which walks
         *     a directory — conflating the two makes a liveness probe do real work.
         */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every open question, filtered, ordered and collapsed
         * @description The queue.
         *
         *     **Every control is a query parameter and none of them is a header or a body**, because a
         *     curator who finds a bad answer must be able to send somebody the link to the screen they
         *     were looking at — spec §4.1.
         */
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark now as seen, for the since-last-visit filter
         * @description **Deliberately not a side effect of reading the queue.** If a GET stamped a visit, the
         *     next GET would have a baseline of a moment ago and *what changed since I last looked*
         *     would be permanently empty — right once, then wrong forever.
         */
        post: operations["markVisited"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Settle one question on one draft
         * @description Settle one question. Three lines, because the logic is a service.
         *
         *     **No `try`.** A `ValueError` from below carries a coded refusal — `MF0002`, `MF0003`, or
         *     the reason check — and `create_app` turns it into a 422 for every route at once, exactly
         *     as the forge does. Catching it here would be a second spelling of one contract,
         *     and the second spelling is the one that drifts.
         */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/answer-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Settle one question on every draft that asks it
         * @description **A partial batch is a 200, not a 207 and not a 422.** The operation did what it was
         *     asked and is reporting what it found; the refusals are in the body with their codes.
         *     A 207 is a status no generated client models usefully.
         */
        post: operations["answerAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline a question — nothing declared fits
         * @description Invariant 7's escape hatch. The hole stays open; `still_open` says so in the payload.
         */
        post: operations["proposeType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/proposals/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve, rename or reject a proposal
         * @description One route, not two. Approve and reject are one decision with a value, and separate
         *     endpoints would let them drift apart.
         */
        post: operations["decideProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the registry holds, and when it was last checked */
        get: operations["registryHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A type's states, and which contracts use it */
        get: operations["lookupType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every contract, worst first */
        get: operations["listContracts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{id}/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What moved between a contract and its source, and what it means */
        get: operations["readDrift"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{id}/drift/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take the source's value for one field */
        post: operations["acceptDrift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One contract, its module, and what points at it */
        get: operations["readContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What can be read, and what has been done */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a draft from a source */
        post: operations["draftTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What needs a person, across both halves */
        get: operations["whatNeedsYou"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptBody */
        AcceptBody: {
            /** Field */
            field: string;
            /** By */
            by: string;
            /** Why */
            why: string;
        };
        /** AcceptResult */
        AcceptResult: {
            /** Contract Id */
            contract_id: string;
            /** Field */
            field: string;
            /** Was */
            was: string;
            /** Now */
            now: string;
            /** Path */
            path: string;
            /** Branch */
            branch: string;
            /** Commit */
            commit: string;
        };
        /** AnswerAllRequest */
        AnswerAllRequest: {
            /** Subject */
            subject: string;
            /** Value */
            value: unknown;
            /** Why */
            why: string;
            /** By */
            by?: string | null;
        };
        /** AnswerRequest */
        AnswerRequest: {
            /** Draft */
            draft: string;
            /** Subject */
            subject: string;
            /** Value */
            value: unknown;
            /** Why */
            why: string;
            /** By */
            by?: string | null;
        };
        /** Answered */
        Answered: {
            /** Draft */
            draft: string;
            /** Subject */
            subject: string;
            /** Remaining */
            remaining: string[];
        };
        /** AnsweredAll */
        AnsweredAll: {
            /** Subject */
            subject: string;
            /** Settled */
            settled: string[];
            /** Refused */
            refused: components["schemas"]["RefusedDraft"][];
        };
        /** Attention */
        Attention: {
            /** Forge */
            forge: components["schemas"]["Call"][];
            /** Mendel */
            mendel: components["schemas"]["Call"][];
            standing: components["schemas"]["Standing"];
        };
        /**
         * Band
         * @description How much a wrong answer costs, which is not the same as how likely one is.
         *
         *     Graded by consequence rather than hit rate — the operator's call on 2026-08-17, after
         *     the forge measured a model at 97% on the fields that change which pipeline gets built
         *     and ~60% on port labels. A flat accuracy number averages those two and hides the only
         *     one worth knowing.
         * @enum {string}
         */
        Band: "drift" | "routing" | "cosmetic" | "prose" | "blocked";
        /**
         * Call
         * @description One thing asking for a person: how much, said plainly, and where it lives.
         */
        Call: {
            /** What */
            what: string;
            /** Where */
            where: string;
            /** Count */
            count: number;
            urgency: components["schemas"]["Urgency"];
        };
        /**
         * Candidate
         * @description One thing that may be answered, and where it comes from.
         *
         *     Not `CandidateRef` — that is `egress.py`'s alias for a *reference* that crosses door 2
         *     (`ContractId | EdgeRef | None`). This is the offered option a reviewer reads.
         */
        Candidate: {
            /** Value */
            value: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Catalogue */
        Catalogue: {
            /** Rows */
            rows: components["schemas"]["ToolRow"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Sources */
            sources: string[];
        };
        /** ContractRow */
        ContractRow: {
            /** Id */
            id: string;
            /** Roles */
            roles: string[];
            /** Source */
            source: string;
            status: components["schemas"]["Status"];
        };
        /** DecideRequest */
        DecideRequest: {
            /** Draft */
            draft: string;
            /** Subject */
            subject: string;
            decision: components["schemas"]["Decision"];
            /** Why */
            why: string;
            /** Id */
            id?: string | null;
            /** By */
            by?: string | null;
        };
        /** Decided */
        Decided: {
            /** Draft */
            draft: string;
            /** Subject */
            subject: string;
            /** Value */
            value: string | null;
            /** Still Open */
            still_open: boolean;
        };
        /**
         * Decision
         * @description What a reviewer said about a proposal.
         *
         *     `OPEN` is the default because a proposal arrives undecided, and a default of anything
         *     else would make an unreviewed proposal look reviewed.
         * @enum {string}
         */
        Decision: "open" | "approved" | "rejected";
        /** Diagnostic */
        Diagnostic: {
            /** Code */
            code: string;
            /** Where */
            where: string;
            /** Summary */
            summary: string;
            /** Detail */
            detail: string;
            /** Fix */
            fix: string;
        };
        /** DraftBody */
        DraftBody: {
            /** Ref */
            ref: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** DraftResult */
        DraftResult: {
            /** Name */
            name: string;
            /** Target */
            target: string;
            /** Holes */
            holes: components["schemas"]["Hole"][];
            /** Filled */
            filled: {
                [key: string]: components["schemas"]["FilledValue"];
            };
            /** Generated Module */
            generated_module: boolean;
        };
        /** DriftReport */
        DriftReport: {
            /** Contract Id */
            contract_id: string;
            /** Verifiable */
            verifiable: boolean;
            /** Module Read */
            module_read: boolean;
            /** Checks */
            checks: components["schemas"]["FieldCheck"][];
            /** Conformance */
            conformance: components["schemas"]["Diagnostic"][];
            /** Unchecked */
            unchecked: components["schemas"]["Unchecked"][];
            verdict: components["schemas"]["Verdict"];
            /** Says */
            says: string;
        };
        /**
         * Excerpt
         * @description A span of source text and a resolvable pointer to it.
         *
         *     `locator` is a `file:line` or a URL — never a bare claim. The rule drafter's §3.2
         *     makes the same demand of a citation for the same reason: a reviewer approving
         *     something is approving that the quoted text supports it, and they cannot do that
         *     without the text.
         *
         *     **A file locator is relative to the root it was read under, never absolute.** An
         *     absolute one carries the machine into every draft and every golden file, which is the
         *     defect issue #46 found in `digest_of_directory` — and it was a golden file that caught
         *     it here too, on the first one written.
         *
         *     **`text` is weaker than this docstring asks for, today.** The nf-core source sets one
         *     excerpt per fact naming the process and the file rather than quoting the line the fact
         *     was read from, because `ModuleSpec` records no line numbers. That is enough to find the
         *     evidence and not enough to read it without opening the file — a real gap, and the right
         *     place to close it is `ModuleSpec`, so that conformance diagnostics gain line numbers at
         *     the same time.
         *
         *     **Moved here from the forge's `observe` module by Plan 2.5.** A build-path question that
         *     quotes its evidence needs the same type, and the forge is where it was first needed rather
         *     than where it belongs.
         *
         *     (Naming that module's package in full here trips `test_no_pure_package_imports_an_impure_one`,
         *     which is a substring scan over the file text rather than an import analysis. The guard is
         *     blunt rather than wrong, and rewording is cheaper than teaching it to read Python.)
         */
        Excerpt: {
            /** Locator */
            locator: string;
            /** Text */
            text: string;
        };
        /** FieldCheck */
        FieldCheck: {
            /** Field */
            field: string;
            impact: components["schemas"]["Impact"];
            /** Registry Says */
            registry_says: string;
            /** Source Says */
            source_says: string;
            /** Agrees */
            agrees: boolean;
            /** Locator */
            locator: string | null;
            /** Excerpt */
            excerpt: string | null;
        };
        /**
         * FilledValue
         * @description A settled hole. Adds nothing to `Answer` — see the spec's §4.2, where that is read
         *     as a signal the base is drawn at about the right place.
         *
         *     `by` is `nf-core` for a derived fact, a username for a hand fill, a model id for a
         *     model one. `land` copies it verbatim into `Provenance.drafted_by`.
         */
        FilledValue: {
            /** Value */
            value: unknown;
            /** By */
            by: string;
            how: components["schemas"]["ValueSource"];
            /** Why */
            why: string;
        };
        /**
         * Grouping
         * @enum {string}
         */
        Grouping: "question" | "module";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Hole
         * @description An unanswered question about a contract being drafted.
         *
         *     **The blocking lives in `Scaffold`, not here.** `Scaffold.is_complete()` gates
         *     `contract_from`, so the forge cannot emit an invalid declared file. Putting that on
         *     this class — as a field or as a method — would trade a structural guarantee for a
         *     runtime check on a value, which is the mistake `CLAUDE.md` records about invariant 1.
         */
        Hole: {
            /** Subject */
            subject: string;
            /**
             * What
             * @default
             */
            what: string;
            /**
             * Why Open
             * @default
             */
            why_open: string;
            /** Candidates */
            candidates?: components["schemas"]["Candidate"][];
            /**
             * Closed
             * @default true
             */
            closed: boolean;
            /** Evidence */
            evidence?: components["schemas"]["Excerpt"][];
            /** After */
            after?: string | null;
            /**
             * Channels
             * @default []
             */
            channels: string[];
        };
        /**
         * Impact
         * @description What reads this field — which is what decides how much a change to it matters.
         * @enum {string}
         */
        Impact: "routes" | "builds" | "records";
        /** Listing */
        Listing: {
            /** Rows */
            rows: components["schemas"]["ContractRow"][];
            /** Total */
            total: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** ModulePage */
        ModulePage: {
            /** Id */
            id: string;
            /** Roles */
            roles: string[];
            /** Container */
            container: string | null;
            /** Consumes */
            consumes: components["schemas"]["Port"][];
            /** Produces */
            produces: components["schemas"]["Port"][];
            /** Source Path */
            source_path: string | null;
            /** Emits Total */
            emits_total: number | null;
            /** Emits Declared */
            emits_declared: number | null;
            /** Rules Aiming */
            rules_aiming: string[];
            /** Inputs From */
            inputs_from: string[];
            /** Outputs Feed */
            outputs_feed: string[];
            /** Competes With */
            competes_with: string[];
            /** Pipeline Pins */
            pipeline_pins?: null;
        };
        /** OpenQuestion */
        OpenQuestion: {
            /** @default question */
            kind: components["schemas"]["RowKind"];
            /** About */
            about?: string | null;
            /** Subject */
            subject: string;
            /** What */
            what: string;
            /** Why Open */
            why_open: string;
            band: components["schemas"]["Band"];
            /** Asked By */
            asked_by: string[];
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /** Closed */
            closed: boolean;
            /** Evidence */
            evidence: components["schemas"]["Excerpt"][];
            /** Suggested */
            suggested?: string | null;
            proposed?: components["schemas"]["Proposal"] | null;
            /** Changed At */
            changed_at?: string | null;
        };
        /**
         * Ordering
         * @enum {string}
         */
        Ordering: "consequence" | "recent";
        /** Port */
        Port: {
            /** Name */
            name: string;
            /** Type Id */
            type_id: string;
        };
        /**
         * Proposal
         * @description What a hole needs that the vocabulary cannot express yet.
         *
         *     **Not a fill.** A hole with a proposal stays open: `is_complete()` is still false and
         *     `contract_from` still refuses, because a contract whose port cites an undeclared type is
         *     the load-time refusal invariant 7 already makes. What a proposal changes is that the hole
         *     now says *why* it is open — "nothing declared fits, and here is what would" — rather than
         *     looking like a field nobody has reached.
         *
         *     **Not a vocabulary file either.** It lives in the workspace draft. Nothing writes
         *     `vocabularies/`; a person moves it, which is invariant 2's approval step and the whole of
         *     what bounds a model inventing an id and a sentence.
         *
         *     See `notes/specs/2026-08-17-vocabulary-proposals.md`.
         */
        Proposal: {
            /** Id */
            id: string;
            /** Description */
            description: string;
            /** Why */
            why: string;
            /** By */
            by: string;
            /** @default open */
            decision: components["schemas"]["Decision"];
            /**
             * Decided By
             * @default
             */
            decided_by: string;
            /**
             * Decided Why
             * @default
             */
            decided_why: string;
            /**
             * Decided Id
             * @default
             */
            decided_id: string;
        };
        /** ProposeRequest */
        ProposeRequest: {
            /** Draft */
            draft: string;
            /** Subject */
            subject: string;
            /** Id */
            id: string;
            /** Description */
            description: string;
            /** Why */
            why: string;
            /** By */
            by?: string | null;
        };
        /** Proposed */
        Proposed: {
            /** Draft */
            draft: string;
            /** Subject */
            subject: string;
            /** Still Open */
            still_open: boolean;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Questions */
            questions: components["schemas"]["OpenQuestion"][];
            /** Total */
            total: number;
        };
        /**
         * Refusal
         * @description A coded refusal. `detail` is `"<code>: <message>"` — `forge explain <code>` expands it.
         */
        Refusal: {
            /** Detail */
            detail: string;
        };
        /** RefusedDraft */
        RefusedDraft: {
            /** Draft */
            draft: string;
            /** Detail */
            detail: string;
        };
        /**
         * RowKind
         * @description What a row IS, which decides where following it leads.
         *
         *     One row shape for every kind of work is firm (design §8), and a row still has to know
         *     whether it leads to a question or to a contract. Derived nowhere and stored here because
         *     it is a fact about the row's origin rather than about its content.
         * @enum {string}
         */
        RowKind: "question" | "drift";
        /**
         * Standing
         * @description What the registry holds. Not what it needs.
         */
        Standing: {
            /** Contracts */
            contracts: number;
            /** Matching */
            matching: number;
            /** Unverifiable */
            unverifiable: number;
            /** Drifted */
            drifted: number;
            /** Types */
            types: number;
            /** Roles */
            roles: number;
            /** Rules */
            rules: number;
            /** Measurements */
            measurements: number;
            /** Sources */
            sources: string[];
            /** Undrafted */
            undrafted: number;
        };
        /**
         * State
         * @enum {string}
         */
        State: "undrafted" | "drafted" | "landed";
        /**
         * Status
         * @enum {string}
         */
        Status: "drifted" | "unverifiable" | "matching";
        /** Strip */
        Strip: {
            /** Contracts */
            contracts: number;
            /** Matching */
            matching: number;
            /** Unverifiable */
            unverifiable: number;
            /** Types */
            types: number;
            /** Checked At */
            checked_at: string | null;
        };
        /** ToolRow */
        ToolRow: {
            /** Ref */
            ref: string;
            state: components["schemas"]["State"];
            /** Contract Id */
            contract_id?: string | null;
            /** Draft */
            draft?: string | null;
        };
        /** TypeCard */
        TypeCard: {
            /** Id */
            id: string;
            /** States */
            states: string[];
            /** Produced By */
            produced_by: string[];
            /** Consumed By */
            consumed_by: string[];
        };
        /** Unchecked */
        Unchecked: {
            /** Field */
            field: string;
            impact: components["schemas"]["Impact"];
            /** Why */
            why: string;
        };
        /**
         * Urgency
         * @description How much a thing costs if it waits — not how likely it is to matter.
         * @enum {string}
         */
        Urgency: "blocking" | "waiting" | "idle";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValueSource
         * @description Who decided a value, recorded separately from how well it was decided.
         *
         *     A tier says *how* something was settled; it should not also have to say *who*. A user
         *     who pins a parameter has legitimately removed the ambiguity, so the tier is still
         *     structural — but a reviewer needs to see that Mendel did not derive it. Same shape as
         *     measured-versus-asserted in the profiling spec, and for the same reason.
         *
         *     **Not `PremiseOrigin`, which also has a `DERIVED`.** That enum answers *how good is this
         *     as evidence*; this one answers *who settled it*. Its own docstring draws the same line,
         *     and the two `DERIVED`s mean different things: there, a fact computed from other facts;
         *     here, a fact read straight off a source file.
         * @enum {string}
         */
        ValueSource: "resolver" | "goal" | "human" | "model" | "measured" | "derived";
        /**
         * Verdict
         * @description The only question a maintainer really has, answered — design §7.
         * @enum {string}
         */
        Verdict: "breaks" | "reroutes" | "rebuilds" | "recorded" | "agrees";
        /** Visited */
        Visited: {
            /**
             * Seen At
             * Format: date-time
             */
            seen_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                /** @description Only this band. */
                band?: components["schemas"]["Band"] | null;
                /** @description One row per question, or per draft. */
                group?: components["schemas"]["Grouping"];
                /** @description Worst-to-get-wrong, or newest. */
                sort?: components["schemas"]["Ordering"];
                /** @description Only what moved since you last looked. */
                since_last_visit?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markVisited: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visited"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answered"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    answerAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerAllRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnsweredAll"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    proposeType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposed"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    decideProposal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decided"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    registryHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strip"];
                };
            };
        };
    };
    lookupType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeCard"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    listContracts: {
        parameters: {
            query?: {
                /** @description Only this status. */
                against?: components["schemas"]["Status"] | null;
                /** @description Only contracts with this role. */
                role?: string | null;
                /** @description Only this namespace. */
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readDrift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftReport"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    acceptDrift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptResult"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    readContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModulePage"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                /** @description Only this state. */
                state?: components["schemas"]["State"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draftTool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResult"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    whatNeedsYou: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
}
