/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is the service up
         * @description Liveness only. What the *registry* looks like is `/health/registry`, which walks
         *     a directory — conflating the two makes a liveness probe do real work.
         */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every open question, collapsed
         * @description Every open question in the workspace, collapsed.
         *
         *     `show` needs the registry and the source as well as the workspace: a hole's candidates
         *     are recomputed from the layer stack rather than stored, so a draft cannot be read
         *     without the registry it was drafted against.
         */
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Settle one question on one draft
         * @description Settle one question. Three lines, because the logic is a service.
         *
         *     **No `try`.** A `ValueError` from below carries a coded refusal — `MF0002`, `MF0003`, or
         *     the reason check — and `create_app` turns it into a 422 for every route at once, exactly
         *     as `mendel_forge.http` does. Catching it here would be a second spelling of one contract,
         *     and the second spelling is the one that drifts.
         */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the registry holds, and when it was last checked */
        get: operations["registryHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerRequest */
        AnswerRequest: {
            /** Draft */
            draft: string;
            /** Subject */
            subject: string;
            /** Value */
            value: unknown;
            /** Why */
            why: string;
            /** By */
            by?: string | null;
        };
        /** Answered */
        Answered: {
            /** Draft */
            draft: string;
            /** Subject */
            subject: string;
            /** Remaining */
            remaining: string[];
        };
        /**
         * Band
         * @description How much a wrong answer costs, which is not the same as how likely one is.
         *
         *     Graded by consequence rather than hit rate — the operator's call on 2026-08-17, after
         *     the forge measured a model at 97% on the fields that change which pipeline gets built
         *     and ~60% on port labels. A flat accuracy number averages those two and hides the only
         *     one worth knowing.
         * @enum {string}
         */
        Band: "routing" | "cosmetic" | "prose";
        /**
         * Candidate
         * @description One thing that may be answered, and where it comes from.
         *
         *     Not `CandidateRef` — that is `egress.py`'s alias for a *reference* that crosses door 2
         *     (`ContractId | EdgeRef | None`). This is the offered option a reviewer reads.
         */
        Candidate: {
            /** Value */
            value: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * Excerpt
         * @description A span of source text and a resolvable pointer to it.
         *
         *     `locator` is a `file:line` or a URL — never a bare claim. The rule drafter's §3.2
         *     makes the same demand of a citation for the same reason: a reviewer approving
         *     something is approving that the quoted text supports it, and they cannot do that
         *     without the text.
         *
         *     **A file locator is relative to the root it was read under, never absolute.** An
         *     absolute one carries the machine into every draft and every golden file, which is the
         *     defect issue #46 found in `digest_of_directory` — and it was a golden file that caught
         *     it here too, on the first one written.
         *
         *     **`text` is weaker than this docstring asks for, today.** The nf-core source sets one
         *     excerpt per fact naming the process and the file rather than quoting the line the fact
         *     was read from, because `ModuleSpec` records no line numbers. That is enough to find the
         *     evidence and not enough to read it without opening the file — a real gap, and the right
         *     place to close it is `ModuleSpec`, so that conformance diagnostics gain line numbers at
         *     the same time.
         *
         *     **Moved here from the forge's `observe` module by Plan 2.5.** A build-path question that
         *     quotes its evidence needs the same type, and the forge is where it was first needed rather
         *     than where it belongs.
         *
         *     (Naming that module's package in full here trips `test_no_pure_package_imports_an_impure_one`,
         *     which is a substring scan over the file text rather than an import analysis. The guard is
         *     blunt rather than wrong, and rewording is cheaper than teaching it to read Python.)
         */
        Excerpt: {
            /** Locator */
            locator: string;
            /** Text */
            text: string;
        };
        /** OpenQuestion */
        OpenQuestion: {
            /** Subject */
            subject: string;
            /** What */
            what: string;
            /** Why Open */
            why_open: string;
            band: components["schemas"]["Band"];
            /** Asked By */
            asked_by: string[];
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /** Closed */
            closed: boolean;
            /** Evidence */
            evidence: components["schemas"]["Excerpt"][];
            /** Suggested */
            suggested?: string | null;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Questions */
            questions: components["schemas"]["OpenQuestion"][];
            /** Total */
            total: number;
        };
        /**
         * Refusal
         * @description A coded refusal. `detail` is `"<code>: <message>"` — `forge explain <code>` expands it.
         */
        Refusal: {
            /** Detail */
            detail: string;
        };
        /** Strip */
        Strip: {
            /** Contracts */
            contracts: number;
            /** Matching */
            matching: number;
            /** Unverifiable */
            unverifiable: number;
            /** Types */
            types: number;
            /** Checked At */
            checked_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    listQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answered"];
                };
            };
            /** @description A coded refusal — `MF0002`, `MF0003`, `MD…`. `forge explain <code>` expands it. A malformed body also answers 422, in FastAPI's validation shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    registryHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strip"];
                };
            };
        };
    };
}
