/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a gated pipeline directory */
        post: operations["uploadArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The board */
        get: operations["listRuns"];
        put?: never;
        /** Run a pipeline */
        post: operations["submitRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A run, projected */
        get: operations["readRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The record, in order
         * @description What the console reads before it subscribes — §7.2's page-then-tail handoff.
         */
        get: operations["readRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The pipeline's own graph, coloured by what the run did
         * @description **Nothing new is computed** — §9.1. The layout is `dag-core`'s, the same one the builder
         *     draws, and the colouring is the fold's. A graph that cannot disagree with either.
         */
        get: operations["readRunGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What each process asked for and what it used
         * @description Per process, worst case kept. The maximum is what kills a run and the mean is what hides
         *     it — §9.3, and the sort is by what took longest because that is what a reader came for.
         */
        get: operations["readRunStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Wiener up */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactStored */
        ArtifactStored: {
            /** Artifact Id */
            artifact_id: string;
            /** Digest */
            digest: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Declared
             * @default []
             */
            declared: string[];
        };
        /** Body_uploadArtifact */
        Body_uploadArtifact: {
            /** Bundle */
            bundle: string;
        };
        /** DrawnWire */
        DrawnWire: {
            /** From Node */
            from_node: string;
            /** From Port */
            from_port: string;
            /** To Node */
            to_node: string;
            /** To Port */
            to_port: string;
            /** Points */
            points: {
                [key: string]: number;
            }[];
            /**
             * Active
             * @default false
             */
            active: boolean;
            /** Bytes Moved */
            bytes_moved?: number | null;
        };
        /**
         * EventPage
         * @description A page of the record, **and where to subscribe from when you have read it**.
         *
         *     The handoff is the only ordering subtlety in the console (§7.2), so it is a field rather
         *     than a convention: page from Postgres, then tail from `stream_id`. A browser that has been
         *     closed for a day does not scroll back through Redis.
         */
        EventPage: {
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
            /** Cursor */
            cursor: number;
            /** Stream Id */
            stream_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlacedNode
         * @description A node, where the layout put it, and what the run did to it.
         */
        PlacedNode: {
            /** Id */
            id: string;
            /** Process */
            process: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Tier */
            tier: number;
            /**
             * Inputs
             * @default []
             */
            inputs: string[];
            /**
             * Outputs
             * @default []
             */
            outputs: string[];
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
        };
        /**
         * ProcessStatsOut
         * @description §9.3's four comparisons for one process. **Absent is not zero** — a `null` here means the
         *     run was launched without `trace.enabled` and nothing was reported.
         */
        ProcessStatsOut: {
            /** Process */
            process: string;
            /** Tasks */
            tasks: number;
            /** Memory Asked Bytes */
            memory_asked_bytes?: number | null;
            /** Memory Peak Bytes */
            memory_peak_bytes?: number | null;
            /** Cpus Asked */
            cpus_asked?: number | null;
            /** Cpu Used Pct */
            cpu_used_pct?: number | null;
            /** Realtime Ms */
            realtime_ms?: number | null;
            /** Queue Wait Ms */
            queue_wait_ms?: number | null;
            /** Read Bytes */
            read_bytes?: number | null;
            /** Write Bytes */
            write_bytes?: number | null;
        };
        /** RunAccepted */
        RunAccepted: {
            /** Run Id */
            run_id: string;
        };
        /** RunGraphOut */
        RunGraphOut: {
            /**
             * Nodes
             * @default []
             */
            nodes: components["schemas"]["PlacedNode"][];
            /**
             * Wires
             * @default []
             */
            wires: components["schemas"]["DrawnWire"][];
            /**
             * Width
             * @default 0
             */
            width: number;
            /**
             * Height
             * @default 0
             */
            height: number;
        };
        /** RunRow */
        RunRow: {
            /** Id */
            id: string;
            /** Phase */
            phase: string;
            /** Executor */
            executor: string;
            /** Submitted By */
            submitted_by: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** SubmitRequest */
        SubmitRequest: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: string | string[];
            };
            /**
             * Executor
             * @default local
             * @constant
             */
            executor: "local";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    uploadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadArtifact"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactStored"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRow"][];
                };
            };
        };
    };
    submitRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRunEvents: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRunGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRunStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessStatsOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
