/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a gated pipeline directory
         * @description **`name` is optional and stays optional.** The browser is the courier and it has the
         *     draft's name to send; `curl -F bundle=@run.zip` has nothing to send and must keep working,
         *     because an air-gapped site uploading a `mendel build` artifact by hand is invariant 13's
         *     customer rather than a degraded one. An artifact with no name reads `run <id>`.
         */
        post: operations["uploadArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The board
         * @description One page of runs, newest first, with each row's task tally beside it.
         */
        get: operations["listRuns"];
        put?: never;
        /** Run a pipeline */
        post: operations["submitRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the board's tiles count
         * @description **Declared before `/runs/{run_id}`**, or FastAPI matches `summary` as a run id and every
         *     request 404s on a run nobody asked for. A literal path and a parameterised one that can
         *     both match are ordered, never disambiguated.
         */
        get: operations["readBoardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A run, projected */
        get: operations["readRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The record, in order
         * @description What the console reads before it subscribes — §7.2's page-then-tail handoff.
         */
        get: operations["readRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The pipeline's own graph, coloured by what the run did
         * @description **Nothing new is computed** — §9.1. The layout is `dag-core`'s, the same one the builder
         *     draws, and the colouring is the fold's. A graph that cannot disagree with either.
         */
        get: operations["readRunGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One row per process the artifact declares
         * @description **It does not 404 on an unreadable artifact** — A192, and deliberately unlike `/graph`.
         *     The counts come from the fold and are true whatever happened to the directory; what is lost
         *     is the declared list, so every row says `declared: false` and the bar has no denominator.
         */
        get: operations["readOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A run's tasks, filtered, sorted and paged
         * @description **A query, never a fold** — A191. `sort` is a closed vocabulary and an unknown value
         *     falls back to `task_id` rather than reaching the database.
         *
         *     **`tag` is scoped to this run and there is no endpoint that lists tags.** Answering *how
         *     did sampleB do* needs only the filter; answering *which samples exist* would be a distinct
         *     query over lab strings, which is the deployment-wide search A200 refused. The table already
         *     shows every tag on the page, so a person picks one from what is in front of them.
         */
        get: operations["readTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What this run held over time, and which curves are honest
         * @description **A query, never a fold** — `rn-blocked`, and A191's rule that a board is a query.
         *
         *     `projection.state_of` replays every event a run ever produced; `run_task.attempts` is a
         *     column holding the same attempts, written by the projection when the row was written. A
         *     5,000-task run is 15,000 events to fold and one indexed `SELECT` to read.
         *
         *     Every decision about *which* curves are honest belongs to `wiener_core.series`, which is
         *     pure and reads no clock. This route reads rows and hands them over.
         */
        get: operations["readSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where every attempt sat in time, packed into lanes
         * @description **A query, never a fold** — the same shape as `/series` one endpoint above.
         *
         *     `page-5` listed the timeline under *"BLOCKED, FAKE, OR NOT YET PROJECTED"*, on the grounds
         *     that attempt windows *"are inside `run_task.attempts` but are not projected as columns"*.
         *     That was true of the columns and never of the data: `Attempt.start_ms` and `complete_ms`
         *     have been written into that JSON since W2, so nothing had to be measured, admitted or
         *     migrated — only read.
         *
         *     **Derived columns were the other option and are the wrong one here.** A191 earned its three
         *     columns so a *table* could `ORDER BY`; the timeline reads every attempt of every task at
         *     once and orders by nothing, so an endpoint over the pure verb is `series`'s shape and this
         *     is `series`'s question.
         *
         *     Every decision about how bars pack, when the stack stops and what an open bar means belongs
         *     to `wiener_core.timeline`, which is pure and reads no clock. This route reads rows and hands
         *     them over.
         */
        get: operations["readTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What a run published
         * @description A directory walk, and deliberately nothing more.
         *
         *     **Nothing here resolves anything** — the 2026-08-19 audit found every registry-touching
         *     screen cost ~250ms warm, and a results list has no reason to be one of them.
         *
         *     **Paged, because a 5,000-task run publishes more than a page.** W2 shipped a console that
         *     fetched once at 200 and subscribed, and it was invisible on every run anybody had because
         *     the largest was five tasks. Same mistake, same file, one endpoint along.
         *
         *     `lab_id` is enforced the way `repository.py`'s header asks: this hands back filenames, and a
         *     filter you can forget is a leak.
         */
        get: operations["readResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Wiener up */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactStored */
        ArtifactStored: {
            /** Artifact Id */
            artifact_id: string;
            /** Digest */
            digest: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Declared
             * @default []
             */
            declared: string[];
            /**
             * Input Form
             * @default direct
             * @enum {string}
             */
            input_form: "direct" | "samplesheet";
            /**
             * Input Columns
             * @default []
             */
            input_columns: string[];
        };
        /**
         * AttemptOut
         * @description One try, with what it ASKED FOR beside what it TOUCHED.
         *
         *     **Both halves, or neither is worth showing.** `peak_rss_bytes` alone says a task touched
         *     47 GB and leaves *was that a lot?* to the reader; `memory_bytes` is the reservation it was
         *     given, and the pair is what makes 36 → 48 → 72 a story rather than three numbers.
         *
         *     Every field is nullable, because a run launched without `trace.enabled` recorded none of
         *     them — **absent rather than zero** (§4.3 finding 6).
         */
        AttemptOut: {
            /** N */
            n: number;
            /** Status */
            status: string;
            /** Exit */
            exit?: number | null;
            /** Signal */
            signal?: string | null;
            /** Memory Bytes */
            memory_bytes?: number | null;
            /** Peak Rss Bytes */
            peak_rss_bytes?: number | null;
            /** Realtime Ms */
            realtime_ms?: number | null;
        };
        /**
         * Bar
         * @description One attempt, where it sat. **Not one task** — see rule 3.
         */
        Bar: {
            /** Task Id */
            task_id: number;
            /** Attempt */
            attempt: number;
            status: components["schemas"]["TaskStatus"];
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms?: number | null;
            /**
             * Row
             * @default 0
             */
            row: number;
        };
        /**
         * BoardSummary
         * @description What the tiles count. **Every field is a tally or a percentile over `run`** — nothing
         *     here folds an event stream, which is what keeps the board a page and not a job.
         */
        BoardSummary: {
            /** Window Days */
            window_days: number;
            /** Failed */
            failed: number;
            /** Running */
            running: number;
            /** Succeeded */
            succeeded: number;
            /** Total */
            total: number;
            /** Median Ms */
            median_ms: number | null;
            /** P95 Ms */
            p95_ms: number | null;
            /** Days */
            days: components["schemas"]["DayCount"][];
            /**
             * By Pipeline
             * @default {}
             */
            by_pipeline: {
                [key: string]: number;
            };
        };
        /** Body_uploadArtifact */
        Body_uploadArtifact: {
            /** Bundle */
            bundle: string;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** Curve */
        Curve: {
            /** Name */
            name: string;
            kind: components["schemas"]["Kind"];
            /** Unit */
            unit: string;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["Point"][];
        };
        /** DayCount */
        DayCount: {
            /** Day */
            day: string;
            /** Succeeded */
            succeeded: number;
            /** Failed */
            failed: number;
        };
        /** DrawnWire */
        DrawnWire: {
            /** From Node */
            from_node: string;
            /** From Port */
            from_port: string;
            /** To Node */
            to_node: string;
            /** To Port */
            to_port: string;
            /** Points */
            points: {
                [key: string]: number;
            }[];
            /**
             * Active
             * @default false
             */
            active: boolean;
            /** Bytes Moved */
            bytes_moved?: number | null;
        };
        /**
         * EventPage
         * @description A page of the record, **and where to subscribe from when you have read it**.
         *
         *     The handoff is the only ordering subtlety in the console (§7.2), so it is a field rather
         *     than a convention: page from Postgres, then tail from `stream_id`. A browser that has been
         *     closed for a day does not scroll back through Redis.
         */
        EventPage: {
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
            /** Cursor */
            cursor: number;
            /** Stream Id */
            stream_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Kind
         * @description How much a curve's shape can be trusted.
         *
         *     **Two members, and the absence of a third is the design.** A peak has no honest shape, so
         *     there is nowhere in this type to record one — which is a stronger guarantee than a comment
         *     asking nobody to try.
         * @enum {string}
         */
        Kind: "exact" | "derived";
        /**
         * Lane
         * @description One process, and every attempt of it.
         */
        Lane: {
            /** Process */
            process: string;
            /** Declared */
            declared: boolean;
            /**
             * Bars
             * @default []
             */
            bars: components["schemas"]["Bar"][];
            /**
             * Rows
             * @default 0
             */
            rows: number;
            /**
             * Dense
             * @default 0
             */
            dense: number;
        };
        /** OverviewOut */
        OverviewOut: {
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["ProcessRowOut"][];
            /**
             * Steps Declared
             * @default 0
             */
            steps_declared: number;
            /**
             * Steps Finished
             * @default 0
             */
            steps_finished: number;
        };
        /**
         * PlacedNode
         * @description A node, where the layout put it, and what the run did to it.
         */
        PlacedNode: {
            /** Id */
            id: string;
            /** Process */
            process: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Tier */
            tier: number;
            /**
             * Inputs
             * @default []
             */
            inputs: string[];
            /**
             * Outputs
             * @default []
             */
            outputs: string[];
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
        };
        /** Point */
        Point: {
            /** At Ms */
            at_ms: number;
            /** Value */
            value: number;
        };
        /**
         * ProcessRowOut
         * @description One process's row. **Absent is not zero** — a `null` here means the run was launched
         *     without `trace.enabled` and nothing was reported, or the run has not reached this process
         *     at all. The interface renders both as a dash and neither as a number.
         *
         *     Mirrored from `wiener_core.ProcessRow` rather than reused, the way `/graph`'s models are:
         *     the wire format is `wiener-api`'s to keep stable, and the pure package's types answer to
         *     the fold. Declared field by field rather than as a `dict`, because the generated client is
         *     what stops the two halves drifting and a `dict` reaches TypeScript as nothing at all.
         */
        ProcessRowOut: {
            /** Process */
            process: string;
            /**
             * Declared
             * @default false
             */
            declared: boolean;
            /**
             * Reached
             * @default false
             */
            reached: boolean;
            /**
             * Tasks
             * @default 0
             */
            tasks: number;
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Cached
             * @default 0
             */
            cached: number;
            /**
             * Attempts Max
             * @default 1
             */
            attempts_max: number;
            /** Memory Asked Bytes */
            memory_asked_bytes?: number | null;
            /** Memory Peak Bytes */
            memory_peak_bytes?: number | null;
            /** Cpus Asked */
            cpus_asked?: number | null;
            /** Cpu Used Pct */
            cpu_used_pct?: number | null;
            /** Realtime Ms */
            realtime_ms?: number | null;
            /** Queue Wait Ms */
            queue_wait_ms?: number | null;
            /** Read Bytes */
            read_bytes?: number | null;
            /** Write Bytes */
            write_bytes?: number | null;
        };
        /**
         * ResultFile
         * @description One published file. Every field is read off the filesystem; nothing is inferred.
         */
        ResultFile: {
            /** Process */
            process: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Modified Ms */
            modified_ms: number;
        };
        /**
         * ResultsOut
         * @description What a run published, and — when it published nothing — which kind of nothing.
         *
         *     **Three absences, and they are different facts.** `rn-absence`'s rule and
         *     `ProcessRow.reported_resources` are the shape being copied: an empty list for all three
         *     would say *this run produced no output* about a run that has not started, about a run whose
         *     pipeline predates publishing entirely, and about a run that genuinely made nothing.
         */
        ResultsOut: {
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["ResultFile"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Published */
            published: boolean;
        };
        /** RunAccepted */
        RunAccepted: {
            /** Run Id */
            run_id: string;
        };
        /** RunGraphOut */
        RunGraphOut: {
            /**
             * Nodes
             * @default []
             */
            nodes: components["schemas"]["PlacedNode"][];
            /**
             * Wires
             * @default []
             */
            wires: components["schemas"]["DrawnWire"][];
            /**
             * Width
             * @default 0
             */
            width: number;
            /**
             * Height
             * @default 0
             */
            height: number;
        };
        /** RunRow */
        RunRow: {
            /** Id */
            id: string;
            /** Phase */
            phase: string;
            /** Executor */
            executor: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Submitted By */
            submitted_by: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Tasks Done
             * @default 0
             */
            tasks_done: number;
            /**
             * Tasks Seen
             * @default 0
             */
            tasks_seen: number;
            /** Pipeline Digest */
            pipeline_digest?: string | null;
        };
        /**
         * RunsPage
         * @description A page of the board, and the total the same filters match.
         */
        RunsPage: {
            /** Runs */
            runs: components["schemas"]["RunRow"][];
            /** Total */
            total: number;
        };
        /**
         * Series
         * @description Every curve a run's attempts can honestly support, and the window they cover.
         */
        Series: {
            /**
             * Curves
             * @default []
             */
            curves: components["schemas"]["Curve"][];
            /**
             * From Ms
             * @default 0
             */
            from_ms: number;
            /**
             * To Ms
             * @default 0
             */
            to_ms: number;
            /**
             * Open
             * @default false
             */
            open: boolean;
            /**
             * Bin Ms
             * @default 0
             */
            bin_ms: number;
            /**
             * Reported Resources
             * @default false
             */
            reported_resources: boolean;
        };
        /** SubmitRequest */
        SubmitRequest: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: string | string[] | {
                    [key: string]: string;
                }[];
            };
            /**
             * Executor
             * @default local
             * @constant
             */
            executor: "local";
        };
        /**
         * TaskOut
         * @description One task row. `tag` is the laboratory's own word for it — A200 — and it is the only
         *     field here that a laboratory wrote.
         */
        TaskOut: {
            /** Task Id */
            task_id: number;
            /** Process */
            process: string;
            /** Status */
            status: string;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /** Latest Exit */
            latest_exit?: number | null;
            /**
             * Last Change Ms
             * @default 0
             */
            last_change_ms: number;
            /** Peak Rss Bytes */
            peak_rss_bytes?: number | null;
            /** Realtime Ms */
            realtime_ms?: number | null;
            /** Pct Cpu */
            pct_cpu?: number | null;
            /** Tag */
            tag?: string | null;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["AttemptOut"][];
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "SUBMITTED" | "RUNNING" | "COMPLETED" | "FAILED" | "ABORTED" | "CACHED";
        /** TasksOut */
        TasksOut: {
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskOut"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** Timeline */
        Timeline: {
            /**
             * Lanes
             * @default []
             */
            lanes: components["schemas"]["Lane"][];
            /**
             * From Ms
             * @default 0
             */
            from_ms: number;
            /**
             * To Ms
             * @default 0
             */
            to_ms: number;
            /**
             * Open
             * @default false
             */
            open: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    uploadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadArtifact"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactStored"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                phase?: string | null;
                who?: string | null;
                executor?: string | null;
                after?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readBoardSummary: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRunEvents: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRunGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTasks: {
        parameters: {
            query?: {
                process?: string | null;
                status?: string | null;
                retried_only?: boolean;
                attempt?: number | null;
                tag?: string | null;
                sort?: string;
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TasksOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readResults: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
