/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a gated pipeline directory */
        post: operations["uploadArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The board
         * @description One page of runs, newest first, with each row's task tally beside it.
         */
        get: operations["listRuns"];
        put?: never;
        /** Run a pipeline */
        post: operations["submitRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the board's tiles count
         * @description **Declared before `/runs/{run_id}`**, or FastAPI matches `summary` as a run id and every
         *     request 404s on a run nobody asked for. A literal path and a parameterised one that can
         *     both match are ordered, never disambiguated.
         */
        get: operations["readBoardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A run, projected */
        get: operations["readRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The record, in order
         * @description What the console reads before it subscribes — §7.2's page-then-tail handoff.
         */
        get: operations["readRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The pipeline's own graph, coloured by what the run did
         * @description **Nothing new is computed** — §9.1. The layout is `dag-core`'s, the same one the builder
         *     draws, and the colouring is the fold's. A graph that cannot disagree with either.
         */
        get: operations["readRunGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One row per process the artifact declares
         * @description **It does not 404 on an unreadable artifact** — A192, and deliberately unlike `/graph`.
         *     The counts come from the fold and are true whatever happened to the directory; what is lost
         *     is the declared list, so every row says `declared: false` and the bar has no denominator.
         */
        get: operations["readOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A run's tasks, filtered, sorted and paged
         * @description **A query, never a fold** — A191. `sort` is a closed vocabulary and an unknown value
         *     falls back to `task_id` rather than reaching the database.
         */
        get: operations["readTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What a run published
         * @description A directory walk, and deliberately nothing more.
         *
         *     **Nothing here resolves anything** — the 2026-08-19 audit found every registry-touching
         *     screen cost ~250ms warm, and a results list has no reason to be one of them.
         *
         *     **Paged, because a 5,000-task run publishes more than a page.** W2 shipped a console that
         *     fetched once at 200 and subscribed, and it was invisible on every run anybody had because
         *     the largest was five tasks. Same mistake, same file, one endpoint along.
         *
         *     `lab_id` is enforced the way `repository.py`'s header asks: this hands back filenames, and a
         *     filter you can forget is a leak.
         */
        get: operations["readResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Wiener up */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactStored */
        ArtifactStored: {
            /** Artifact Id */
            artifact_id: string;
            /** Digest */
            digest: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Declared
             * @default []
             */
            declared: string[];
        };
        /**
         * BoardSummary
         * @description What the tiles count. **Every field is a tally or a percentile over `run`** — nothing
         *     here folds an event stream, which is what keeps the board a page and not a job.
         */
        BoardSummary: {
            /** Window Days */
            window_days: number;
            /** Failed */
            failed: number;
            /** Running */
            running: number;
            /** Succeeded */
            succeeded: number;
            /** Total */
            total: number;
            /** Median Ms */
            median_ms: number | null;
            /** P95 Ms */
            p95_ms: number | null;
            /** Days */
            days: components["schemas"]["DayCount"][];
        };
        /** Body_uploadArtifact */
        Body_uploadArtifact: {
            /** Bundle */
            bundle: string;
        };
        /** DayCount */
        DayCount: {
            /** Day */
            day: string;
            /** Succeeded */
            succeeded: number;
            /** Failed */
            failed: number;
        };
        /** DrawnWire */
        DrawnWire: {
            /** From Node */
            from_node: string;
            /** From Port */
            from_port: string;
            /** To Node */
            to_node: string;
            /** To Port */
            to_port: string;
            /** Points */
            points: {
                [key: string]: number;
            }[];
            /**
             * Active
             * @default false
             */
            active: boolean;
            /** Bytes Moved */
            bytes_moved?: number | null;
        };
        /**
         * EventPage
         * @description A page of the record, **and where to subscribe from when you have read it**.
         *
         *     The handoff is the only ordering subtlety in the console (§7.2), so it is a field rather
         *     than a convention: page from Postgres, then tail from `stream_id`. A browser that has been
         *     closed for a day does not scroll back through Redis.
         */
        EventPage: {
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
            /** Cursor */
            cursor: number;
            /** Stream Id */
            stream_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OverviewOut */
        OverviewOut: {
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["ProcessRowOut"][];
            /**
             * Steps Declared
             * @default 0
             */
            steps_declared: number;
            /**
             * Steps Finished
             * @default 0
             */
            steps_finished: number;
        };
        /**
         * PlacedNode
         * @description A node, where the layout put it, and what the run did to it.
         */
        PlacedNode: {
            /** Id */
            id: string;
            /** Process */
            process: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Tier */
            tier: number;
            /**
             * Inputs
             * @default []
             */
            inputs: string[];
            /**
             * Outputs
             * @default []
             */
            outputs: string[];
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
        };
        /**
         * ProcessRowOut
         * @description One process's row. **Absent is not zero** — a `null` here means the run was launched
         *     without `trace.enabled` and nothing was reported, or the run has not reached this process
         *     at all. The interface renders both as a dash and neither as a number.
         *
         *     Mirrored from `wiener_core.ProcessRow` rather than reused, the way `/graph`'s models are:
         *     the wire format is `wiener-api`'s to keep stable, and the pure package's types answer to
         *     the fold. Declared field by field rather than as a `dict`, because the generated client is
         *     what stops the two halves drifting and a `dict` reaches TypeScript as nothing at all.
         */
        ProcessRowOut: {
            /** Process */
            process: string;
            /**
             * Declared
             * @default false
             */
            declared: boolean;
            /**
             * Reached
             * @default false
             */
            reached: boolean;
            /**
             * Tasks
             * @default 0
             */
            tasks: number;
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Cached
             * @default 0
             */
            cached: number;
            /**
             * Attempts Max
             * @default 1
             */
            attempts_max: number;
            /** Memory Asked Bytes */
            memory_asked_bytes?: number | null;
            /** Memory Peak Bytes */
            memory_peak_bytes?: number | null;
            /** Cpus Asked */
            cpus_asked?: number | null;
            /** Cpu Used Pct */
            cpu_used_pct?: number | null;
            /** Realtime Ms */
            realtime_ms?: number | null;
            /** Queue Wait Ms */
            queue_wait_ms?: number | null;
            /** Read Bytes */
            read_bytes?: number | null;
            /** Write Bytes */
            write_bytes?: number | null;
        };
        /**
         * ResultFile
         * @description One published file. Every field is read off the filesystem; nothing is inferred.
         */
        ResultFile: {
            /** Process */
            process: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Modified Ms */
            modified_ms: number;
        };
        /**
         * ResultsOut
         * @description What a run published, and — when it published nothing — which kind of nothing.
         *
         *     **Three absences, and they are different facts.** `rn-absence`'s rule and
         *     `ProcessRow.reported_resources` are the shape being copied: an empty list for all three
         *     would say *this run produced no output* about a run that has not started, about a run whose
         *     pipeline predates publishing entirely, and about a run that genuinely made nothing.
         */
        ResultsOut: {
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["ResultFile"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Published */
            published: boolean;
        };
        /** RunAccepted */
        RunAccepted: {
            /** Run Id */
            run_id: string;
        };
        /** RunGraphOut */
        RunGraphOut: {
            /**
             * Nodes
             * @default []
             */
            nodes: components["schemas"]["PlacedNode"][];
            /**
             * Wires
             * @default []
             */
            wires: components["schemas"]["DrawnWire"][];
            /**
             * Width
             * @default 0
             */
            width: number;
            /**
             * Height
             * @default 0
             */
            height: number;
        };
        /** RunRow */
        RunRow: {
            /** Id */
            id: string;
            /** Phase */
            phase: string;
            /** Executor */
            executor: string;
            /** Submitted By */
            submitted_by: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Tasks Done
             * @default 0
             */
            tasks_done: number;
            /**
             * Tasks Seen
             * @default 0
             */
            tasks_seen: number;
        };
        /**
         * RunsPage
         * @description A page of the board, and the total the same filters match.
         */
        RunsPage: {
            /** Runs */
            runs: components["schemas"]["RunRow"][];
            /** Total */
            total: number;
        };
        /** SubmitRequest */
        SubmitRequest: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: string | string[];
            };
            /**
             * Executor
             * @default local
             * @constant
             */
            executor: "local";
        };
        /**
         * TaskOut
         * @description One task row. `tag` is the laboratory's own word for it — A200 — and it is the only
         *     field here that a laboratory wrote.
         */
        TaskOut: {
            /** Task Id */
            task_id: number;
            /** Process */
            process: string;
            /** Status */
            status: string;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /** Latest Exit */
            latest_exit?: number | null;
            /**
             * Last Change Ms
             * @default 0
             */
            last_change_ms: number;
            /** Peak Rss Bytes */
            peak_rss_bytes?: number | null;
            /** Realtime Ms */
            realtime_ms?: number | null;
            /** Pct Cpu */
            pct_cpu?: number | null;
            /** Tag */
            tag?: string | null;
        };
        /** TasksOut */
        TasksOut: {
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskOut"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    uploadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadArtifact"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactStored"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                phase?: string | null;
                who?: string | null;
                executor?: string | null;
                after?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readBoardSummary: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRunEvents: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readRunGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readTasks: {
        parameters: {
            query?: {
                process?: string | null;
                status?: string | null;
                retried_only?: boolean;
                attempt?: number | null;
                sort?: string;
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TasksOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readResults: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
