"""One Markdown page per tool, rendered from declared data and nothing else.

**Pure.** Takes loaded layers, returns strings. `cli/layer_verbs.py` is the only thing that
touches disk, which is what makes these tests golden-file tests rather than filesystem tests —
the same split `cli/__init__.py` describes and for the same reason.

comeni-registry#2.
"""

from collections import defaultdict

from comeni_core.declared.contract import ModuleContract
from comeni_core.declared.registry import Registry


def _tool_of(contract_id: str) -> str:
    """`nf-core/star/align@1.11.0` -> `nf-core/star`.

    The **module key** — the id minus `@version` — is what shadowing already keys on, so a
    version bump never splits a page in two.

    The first two segments, because the ids are **not uniformly shaped**: `nf-core/star/align`
    has three and `nf-core/fastqc` has two, so "drop the last segment" turns the second into
    `nf-core` and collapses every nf-core module onto one page. That was checked against the
    whole registry rather than reasoned about.

    Fewer than two segments returns the key itself rather than refusing. No contract has one
    today, and a laboratory's in-house `sortmerna@4.3.6` is not obviously wrong — inventing a
    rule for a case that does not exist is how a closed vocabulary comes to forbid something
    legitimate.
    """
    key = contract_id.split("@")[0]
    return "/".join(key.split("/")[:2])


def tools_of(registry: Registry) -> dict[str, list[ModuleContract]]:
    """Every contract in the stack, grouped into the page it belongs on.

    Sorted at both levels. A generated file that reorders itself between runs is a file whose
    `--check` fails for a reason nobody can act on, which is the same hazard `IREdge.states`
    carries a `field_serializer` for.
    """
    grouped: dict[str, list[ModuleContract]] = defaultdict(list)
    for contract_id in sorted(registry.contracts):
        grouped[_tool_of(contract_id)].append(registry.contracts[contract_id])
    return dict(sorted(grouped.items()))


_BANNER = "<!-- Generated by `mendel docs`. Do not edit: `--check` refuses a hand edit. -->"


def _states(states) -> str:
    """Sorted, because a frozenset has no stable order and `--check` compares bytes.

    Same hazard as `IREdge.states`, which carries a `field_serializer` for it. Here it is
    worse than a reordered diff: the pages are committed, so an unsorted set would make CI
    red on a machine whose `PYTHONHASHSEED` differs from the one that generated them.
    """
    return ", ".join(f"`{state}`" for state in sorted(states)) if states else "—"


def _ports(contract: ModuleContract) -> list[str]:
    lines = ["| Direction | Port | Type | States |", "|---|---|---|---|"]
    for port in contract.consumes:
        # `accepts` is the alternative to `type_id`: a port that takes any of several types
        # declares one and not the other, and the contract model refuses both or neither.
        type_id = port.type_id or " / ".join(f"`{a}`" for a in sorted(port.accepts or []))
        shown = f"`{type_id}`" if port.type_id else type_id
        lines.append(f"| consumes | `{port.name}` | {shown} | {_states(port.state_required)} |")
    for port in contract.produces:
        lines.append(f"| produces | `{port.name}` | `{port.type_id}` | {_states(port.state)} |")
    return lines


def _params(contract: ModuleContract) -> list[str]:
    if not contract.params:
        return ["This contract declares no parameters."]
    lines = ["| Parameter | Tier hint | Route | Default |", "|---|---|---|---|"]
    for param in sorted(contract.params, key=lambda p: p.name):
        via = f"`{param.via.value}`" if param.via is not None else "—"
        default = f"`{param.default}`" if param.default is not None else "—"
        # `None` is a real answer — the contract offers no hint and the ladder decides — but
        # rendering the Python literal leaks the implementation into a page a biologist reads.
        hint = param.tier_hint if param.tier_hint is not None else "—"
        lines.append(f"| `{param.name}` | {hint} | {via} | {default} |")
    return lines


def _contract_section(contract: ModuleContract) -> list[str]:
    provenance = contract.provenance
    roles = ", ".join(f"`{role}`" for role in sorted(contract.roles)) or "—"
    return [
        f"### `{contract.id}`",
        "",
        f"- **Process:** `{contract.nf_process}`",
        f"- **Include:** `{contract.nf_include}`",
        f"- **Roles:** {roles}",
        f"- **Container:** `{contract.container}`" if contract.container else "- **Container:** —",
        f"- **Priority:** {contract.priority}",
        "",
        "#### Ports",
        "",
        *_ports(contract),
        "",
        "#### Parameters",
        "",
        *_params(contract),
        "",
        "#### Provenance",
        "",
        f"- source: `{provenance.source}`",
        f"- drafted_by: `{provenance.drafted_by}`",
        f"- approved_by: `{provenance.approved_by}`",
        f"- approved_at: `{provenance.approved_at}`",
        "",
    ]


def render(tool: str, contracts: list[ModuleContract], loaded) -> str:
    """One page. Every line traces to a field of a declared file.

    No hand-written sections and no splice markers: issue #41 found that a generator writing
    into a partly hand-edited page reads the surrounding text back out of the file it is
    comparing against, so the hand-written half is equal to itself by construction and an
    edit there can never be seen. The whole page is generated and `--check` refuses any local
    change.
    """
    lines = [
        _BANNER,
        "",
        f"# {tool}",
        "",
        f"{len(contracts)} contract(s) in this layer stack.",
        "",
    ]
    for contract in contracts:
        lines += _contract_section(contract)
    return "\n".join(lines).rstrip("\n") + "\n"
