#!/usr/bin/env python
"""Render `docs/tools/catalogue.md` — a browsable index of the pages `mendel docs` just wrote.

`mendel docs --registry <layer> --out docs/tools/` writes one page per tool, nested one
directory per registry org (`docs/tools/nf-core/fastqc.md`). Nothing else names those pages —
core MkDocs `nav:` has no directory or glob form, and the set is a function of `--registry` so
it cannot be written into `mkdocs.yml` by hand. Without this, the only way to reach a tool page
is to already know its URL or to search for it, and a catalogue you can only search is not a
catalogue.

Grouping by org is a stand-in for "by role" until roles are declared data a page can group by.

Run by `make wiki-tools`, after `mendel docs` and before `mkdocs build`. The output is
gitignored like every other page under `docs/tools/` — `docs/tools/index.md` is the only
authored file there, and this script's whole job is to make the generated ones reachable
without becoming one.

`build_catalogue` is separated from `main` so a test can run it against a temp directory of
real generated pages without touching `docs/tools/` — the same split `tool_docs.py` describes
between deciding page content and writing it to disk.
"""

import sys
from pathlib import Path

TOOLS_DIR = Path(__file__).parent.parent / "docs" / "tools"
OUT = TOOLS_DIR / "catalogue.md"

HEADER = """<!-- Generated by tools/generate_tools_catalogue.py. Do not edit: `make wiki-tools`
     overwrites it on every build. -->

# Catalogue

Every tool in the registry this site was built against, grouped by the org that supplies it.
"""


def build_catalogue(tools_dir: Path) -> str:
    """The catalogue's content for the tool pages found under `tools_dir`, or `""` if none."""
    by_org: dict[str, list[Path]] = {}
    for path in sorted(tools_dir.glob("*/*.md")):
        by_org.setdefault(path.parent.name, []).append(path)

    if not by_org:
        return ""

    lines = [HEADER]
    for org in sorted(by_org):
        lines.append(f"## {org}\n")
        for path in sorted(by_org[org], key=lambda p: p.stem):
            lines.append(f"- [{org}/{path.stem}]({org}/{path.name})")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    content = build_catalogue(TOOLS_DIR)

    if not content:
        print(
            "generate_tools_catalogue: no tool pages under docs/tools/ — run `mendel docs` "
            "(or `make wiki-tools`) first",
            file=sys.stderr,
        )
        return 1

    OUT.write_text(content, encoding="utf-8")
    tool_count = sum(1 for line in content.splitlines() if line.startswith("- ["))
    org_count = sum(1 for line in content.splitlines() if line.startswith("## "))
    relative = OUT.relative_to(TOOLS_DIR.parent.parent)
    print(f"wrote {relative} ({tool_count} tools, {org_count} orgs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
