#!/usr/bin/env python
"""Render `docs/design/diagrams/` from `mendel_api.authoring.protocol`: the general diagram, one
page per detailed diagram, and an index.

Whole generated files, not blocks spliced into the hand-written protocol page:
`generate_diagnostics_doc.py` records why (`--check` could only ever see the block). **The
folder is checked whole**: a stale page, a missing one and one nothing generates any more (a
detail that was deleted) all fail `--check`.
"""

import sys
from pathlib import Path

from mendel_api.authoring.protocol import PROTOCOL, Protocol, to_mermaid

DIAGRAMS = Path(__file__).parent.parent / "docs" / "design" / "diagrams"

FENCE = "`" * 3
BANNER = "<!-- generated by tools/generate_protocol_doc.py — do not edit -->\n"


def _parents() -> dict[str, str]:
    """Each detail's slug → the label of the node it details, on one line."""
    found = {}

    def walk(protocol: Protocol) -> None:
        for node in protocol.nodes:
            if node.detail is not None:
                found[node.detail.slug] = node.label.replace("<br/>", " ")
                walk(node.detail)

    walk(PROTOCOL)
    return found


def _header(protocol: Protocol) -> str:
    lines = [BANNER, f"# {protocol.title}", ""]
    lines.append(
        "**Generated from `mendel_api/authoring/protocol.py`**, which is also where the running "
        "state machine comes from, so this picture is the machine. Solid is built; dashed is "
        "designed and not built yet. The rules, the argument and the changelog are on "
        "[the protocol page](../authoring-protocol.md)."
    )
    if protocol is not PROTOCOL:
        where = (
            " Everything here happens on our server."
            if all(s.title.startswith("On our server") for s in protocol.stages)
            else ""
        )
        lines += ["", f"A detail of [the authoring protocol](authoring-protocol.md).{where}"]
    return "\n".join(lines) + "\n\n"


def _page(protocol: Protocol) -> str:
    return f"{_header(protocol)}{FENCE}mermaid\n{to_mermaid(protocol)}{FENCE}\n"


def _index(every: list[Protocol]) -> str:
    parents = _parents()
    lines = [BANNER, "# Diagrams", ""]
    for protocol in every:
        if protocol is PROTOCOL:
            says = "the whole conversation, from what you want to what is built"
        else:
            says = f"the steps inside *{parents[protocol.slug]}*"
        lines.append(f"- [{protocol.title}]({protocol.slug}.md): {says}")
    return "\n".join(lines) + "\n"


def pages() -> dict[str, str]:
    every = [PROTOCOL, *PROTOCOL.details()]
    found = {f"{p.slug}.md": _page(p) for p in every}
    found["README.md"] = _index(every)
    return found


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    want = pages()
    have = {p.name for p in DIAGRAMS.glob("*.md")} if DIAGRAMS.exists() else set()
    if "--check" in argv:
        wrong = sorted(
            name
            for name, text in want.items()
            if not (DIAGRAMS / name).exists() or (DIAGRAMS / name).read_text() != text
        )
        orphaned = sorted(have - set(want))
        for name in wrong + orphaned:
            print(
                f"docs/design/diagrams/{name} disagrees with protocol.py — run: "
                "uv run python tools/generate_protocol_doc.py"
            )
        return 1 if wrong or orphaned else 0
    DIAGRAMS.mkdir(parents=True, exist_ok=True)
    for name in sorted(have - set(want)):
        (DIAGRAMS / name).unlink()
    for name, text in want.items():
        (DIAGRAMS / name).write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
