"""Declarations to a typed stub. Derived, never authoritative.

`DataProfile.get` returns a union at runtime because the value type depends on the
measurement, and the declaration knows more than Python does. `Literal` overloads close
that gap for every editor and type checker — PEP 561 stubs work in mypy, pyright, Pylance
and PyCharm alike, where a mypy plugin would work only in mypy and therefore not in
Pylance, which is what most people actually use.

A stale stub costs autocomplete and never correctness, which is the property that makes
generation safe here. `--check` is what stops it rotting unnoticed.

A `.pyi` **replaces** its module for a type checker rather than adding to it, so this file
declares the whole public surface of `comeni_core.profile`, not only the overloads. A stub
covering half a module makes the other half invisible — which is a correctness cost, and
would have voided the paragraph above.
"""

import sys
from pathlib import Path

from comeni_core.measurement import MeasurementKind, MeasurementRegistry

ROOT = Path(__file__).parent.parent
STUB = ROOT / "packages/comeni-core/src/comeni_core/profile.pyi"
REGISTRY = ROOT / "registry"

_RETURN = {
    MeasurementKind.INTEGER: "int | None",
    MeasurementKind.NUMBER: "float | None",
    MeasurementKind.BOOLEAN: "bool | None",
}

_HEADER = '''# Generated by tools/generate_types.py. Do not edit.
# Derived from registry/measurements/. Stale costs autocomplete, never correctness.
#
# A .pyi replaces its module for a type checker, so everything public in
# comeni_core.profile is declared here — not only the overloads that motivated it.
from typing import Literal, overload

from pydantic import BaseModel

from comeni_core.marks import ContractId, MeasurementId, ParamValue
from comeni_core.tiers import ValueSource

class Measured(BaseModel):
    measurement: MeasurementId
    value: ParamValue
    source: ValueSource
    by: ContractId | None

class DataProfile(BaseModel):
    measurements: list[Measured]
'''


def _returns(measurement) -> str:
    if measurement.kind is MeasurementKind.ENUM:
        values = ", ".join(f'"{v}"' for v in measurement.values)
        return f"Literal[{values}] | None"
    return _RETURN[measurement.kind]


def generate_stub(registry: MeasurementRegistry) -> str:
    lines = _HEADER.splitlines()
    for measurement_id in registry.ids():
        argument = f'measurement_id: Literal["{measurement_id}"]'
        returns = _returns(registry.get(measurement_id))
        one_line = f"    def get(self, {argument}) -> {returns}: ..."
        # An enum with several values overruns the line limit, and a generated file that
        # fails `ruff check` is a generated file somebody edits by hand.
        lines.append("    @overload")
        if len(one_line) <= 100:
            lines.append(one_line)
        else:
            lines += [
                "    def get(",
                f"        self, {argument}",
                f"    ) -> {returns}: ...",
            ]
    lines += [
        "    @overload",
        "    def get(self, measurement_id: str) -> ParamValue: ...",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    generated = generate_stub(MeasurementRegistry.load(REGISTRY))
    if "--check" in sys.argv:
        current = STUB.read_text() if STUB.exists() else ""
        if current != generated:
            print(f"{STUB.name} is stale — run: uv run python tools/generate_types.py")
            return 1
        return 0
    STUB.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
