#!/usr/bin/env python
"""Render `docs/reference/diagnostics.md` from `comeni_core/diagnostics.yml`.

One source, two consumers: `Diagnostic` validates its `code` against the registry, and this
renders the public table from it. Before this, the long form lived in a Python dict and the
table was maintained by hand, so a code could exist in one and not the other — and nothing
would say so.

`--check` is what CI runs, on pull requests through `make check` and against `main` through the
nightly workflow. **Nothing commits the regenerated file.** An Action that fixed `main`
automatically would need push rights to a protected branch, and a bypass exists forever and for
everything; worse, a self-healing `main` means nobody ever sees the drift — someone hand-edits
the generated table, a bot silently reverts them, and they learn nothing about why the file is
generated. A failing check teaches.

Deliberately the same shape as `tools/generate_types.py`: compare, print the command that fixes
it, exit 1. A second convention for one job is how one of them rots.

**The whole file is generated, not a block spliced into a hand-written one.** It used to be a
`BEGIN`/`END` pair inside `docs/reference/cli.md`, which had two costs. The codes were two-thirds
of the way down a page about command-line flags, where issue #41 records not finding them; and
`--check` could only ever see the block, because everything outside the markers was read back out
of the file it was comparing against. A hand-edited heading was preserved and reported fresh.
"""

import sys
from pathlib import Path

from comeni_core.diagnostics import REGISTRY, DiagnosticSpec

DOC = Path(__file__).parent.parent / "docs" / "reference" / "diagnostics.md"

HEADER = """<!-- generated by tools/generate_diagnostics_doc.py — do not edit -->

# Diagnostic codes

Every code Mendel can emit, what it says, and whether it refuses. Run `mendel explain <code>`
for the long form — the fix, and the argument for why it is refused at all.

```bash
uv run mendel explain MD0104
```

| band | concern |
|---|---|
| `MD0001`–`MD0099` | loading declared registry data |
| `MD0100`–`MD0199` | a contract disagrees with its module |
| `MD0200`–`MD0299` | the pipeline file — a setting, an override, or the format |
| `MD0300`–`MD0399` | routing and resolution |

Codes carry a two-letter prefix naming the subsystem that emits them. **`MD` is Mendel's
deterministic core** — the resolver, the compiler, contracts and the pipeline file. Bands of one
hundred group by concern, and a code is never renumbered once published, so a full band overflows
into a new one rather than shifting.

**The prefix arrived on 2026-08-09**; the first eight were `M0100`–`M0107` before that. Working
notes under `notes/` are append-only and were correct on their date, so entries written earlier
still use the old spelling.

**`MD0100` is not a failure.** A laboratory wrapping a bare container has no nf-core-style module
directory, which is legitimate — the contract is listed under `registry.unverified` in
`pipeline.yml`, so a shared pipeline carries which claims went unchecked and a curator may
decline to curate one.

"""

HEADINGS: dict[str, str] = {
    "loading": "Loading declared registry data",
    "conformance": "A contract disagrees with its module",
    "pipeline-file": "The pipeline file — a setting, an override, or the format",
    "routing": "Routing and resolution",
    "gates": "Gates and emission",
    "scaffolding": "The forge — a scaffold, its holes, and filling them",
    "verification": "The forge — whether a draft holds up",
    "workspace": "The forge — drafts on disk",
    "landing": "The forge — landing a draft into a registry",
    "model-access": "Reaching a model",
    "model-output": "What a model answered",
}
"""Section titles per `concern`, in the order they are rendered.

Declared here rather than derived from the registry so the document's order is stable and
readable — sorting concerns alphabetically would put "gates" before "conformance", which is
neither the order a reader meets them in nor the order of the bands.
"""


def _rows(specs: list[DiagnosticSpec]) -> list[str]:
    return [f"| `{spec.code}` | {spec.says} |" for spec in sorted(specs, key=lambda s: s.code)]


def table() -> str:
    """The whole generated block, grouped by concern.

    A concern with no codes renders nothing rather than an empty table: the bands are reserved
    ahead of use, and an empty section reads as a gap rather than as a reservation.
    """
    lines: list[str] = []
    for concern, heading in HEADINGS.items():
        specs = [spec for spec in REGISTRY.values() if spec.concern == concern]
        if not specs:
            continue
        lines += [f"## {heading}", "", "| Code | Says |", "|---|---|", *_rows(specs), ""]

    unknown = sorted({s.concern for s in REGISTRY.values()} - set(HEADINGS))
    if unknown:
        raise SystemExit(
            f"diagnostics.yml declares concerns with no heading in this file: {unknown}. "
            "Add them to HEADINGS, in the order a reader should meet them."
        )
    return "\n".join(lines).rstrip("\n")


def rendered() -> str:
    return f"{HEADER}{table()}\n"


def main() -> int:
    generated = rendered()
    if "--check" in sys.argv:
        if DOC.read_text() != generated:
            print(
                f"{DOC.relative_to(DOC.parent.parent.parent)} is stale — run: "
                "uv run python tools/generate_diagnostics_doc.py"
            )
            return 1
        return 0
    DOC.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
