"""Declarations to a typed stub. Derived, never authoritative.

`DataProfile.get` returns a union at runtime because the value type depends on the
measurement, and the declaration knows more than Python does. `Literal` overloads close
that gap for every editor and type checker — PEP 561 stubs work in mypy, pyright, Pylance
and PyCharm alike, where a mypy plugin would work only in mypy and therefore not in
Pylance, which is what most people actually use.

A stale stub costs autocomplete and never correctness, which is the property that makes
generation safe here. `--check` is what stops it rotting unnoticed.

A `.pyi` **replaces** its module for a type checker rather than adding to it, so this file
declares the whole public surface of `comeni_core.goal.profile`, not only the overloads. A stub
covering half a module makes the other half invisible — which is a correctness cost, and
would have voided the paragraph above.
"""

import sys
import textwrap
from pathlib import Path

from comeni_core.declared.measurement import MeasurementKind, MeasurementRegistry

ROOT = Path(__file__).parent.parent
STUB = ROOT / "packages/comeni-core/src/comeni_core/goal/profile.pyi"
REGISTRY = ROOT / "registry"

_RETURN = {
    MeasurementKind.INTEGER: "int | None",
    MeasurementKind.NUMBER: "float | None",
    MeasurementKind.BOOLEAN: "bool | None",
}

_HEADER = '''# Generated by tools/generate_types.py. Do not edit.
# Derived from registry/measurements/. Stale costs autocomplete, never correctness.
#
# A .pyi replaces its module for a type checker, so everything public in
# comeni_core.goal.profile is declared here — not only the overloads that motivated it.
from typing import Literal, overload

from pydantic import BaseModel

from comeni_core.plan.tiers import ValueSource
from comeni_core.spell.marks import ContractId, MeasurementId, ParamValue

class Measured(BaseModel):
    measurement: MeasurementId
    value: ParamValue | list[ParamValue]
    source: ValueSource
    by: ContractId | None

class DataProfile(BaseModel):
    measurements: list[Measured]
'''


def _returns(measurement) -> str:
    """The declared type of `DataProfile.get(<this measurement>)`.

    A `per_sample` measurement may hold a scalar or a list — a scalar being the claim that
    the cohort is uniform — so the overload has to admit both. Emitting the scalar alone
    would be a stub that lies about a shape the loader accepts, which is the failure mode
    this file's own header calls the expensive one: stale costs autocomplete, wrong costs
    correctness.
    """
    if measurement.kind is MeasurementKind.ENUM:
        values = ", ".join(f'"{v}"' for v in measurement.values)
        scalar = f"Literal[{values}]"
    else:
        scalar = _RETURN[measurement.kind].removesuffix(" | None")
    if measurement.per_sample:
        return f"{scalar} | list[{scalar}] | None"
    return f"{scalar} | None"


def _wrapped(returns: str) -> list[str]:
    """`Literal["a", "b", …] | None` broken across lines that fit inside 100 characters.

    Broken inside the brackets `Literal[` already provides, so no continuation marker and no
    change of meaning — the alternative, shortening a declared value to fit a line limit,
    would let a formatting constraint edit the vocabulary.
    """
    head, _, rest = returns.partition("[")
    values, _, tail = rest.rpartition("]")
    return [
        f"{head}[",
        *(f"    {line}" for line in textwrap.wrap(values, width=100 - 12)),
        f"]{tail}",
    ]


def generate_stub(registry: MeasurementRegistry) -> str:
    lines = _HEADER.splitlines()
    for measurement_id in registry.ids():
        argument = f'measurement_id: Literal["{measurement_id}"]'
        returns = _returns(registry.get(measurement_id))
        one_line = f"    def get(self, {argument}) -> {returns}: ..."
        split = f"    ) -> {returns}: ..."
        # An enum with several values overruns the line limit, and a generated file that
        # fails `ruff check` is a generated file somebody edits by hand.
        #
        # Three forms rather than two: splitting the signature was assumed to be enough and
        # was not. `purpose`'s four values make the *return* 101 characters on a line of its
        # own, so the second form failed the check the first form exists to pass — found by
        # adding the measurement, not by reading this. The third wraps inside `Literal[`,
        # which has no length at which it stops working.
        lines.append("    @overload")
        if len(one_line) <= 100:
            lines.append(one_line)
        elif len(split) <= 100:
            lines += ["    def get(", f"        self, {argument}", split]
        else:
            lines += [
                "    def get(",
                f"        self, {argument}",
                "    ) -> (",
                *(f"        {part}" for part in _wrapped(returns)),
                "    ): ...",
            ]
    lines += [
        "    @overload",
        "    def get(self, measurement_id: str) -> ParamValue | list[ParamValue]: ...",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    generated = generate_stub(MeasurementRegistry.load(REGISTRY))
    if "--check" in sys.argv:
        current = STUB.read_text() if STUB.exists() else ""
        if current != generated:
            print(f"{STUB.name} is stale — run: uv run python tools/generate_types.py")
            return 1
        return 0
    STUB.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
