#!/usr/bin/env python
"""Render `docs/design/authoring-protocol-diagram.md` from `mendel_api.authoring.protocol`.

A whole generated file, not a block spliced into the hand-written protocol page:
`generate_diagnostics_doc.py` records why (`--check` could only ever see the block).
"""

import sys
from pathlib import Path

from mendel_api.authoring.protocol import PROTOCOL, to_mermaid

DOC = Path(__file__).parent.parent / "docs" / "design" / "authoring-protocol-diagram.md"

FENCE = "`" * 3

HEADER = """<!-- generated by tools/generate_protocol_doc.py — do not edit -->

# The authoring protocol, drawn

**Generated from `mendel_api/authoring/protocol.py`**, which is also where the running state
machine comes from, so this picture is the machine. Solid is built; dashed is designed and not
built yet. The rules, the argument and the changelog are on
[the protocol page](authoring-protocol.md).

"""


def render() -> str:
    return f"{HEADER}{FENCE}mermaid\n{to_mermaid(PROTOCOL)}{FENCE}\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not DOC.exists() or DOC.read_text() != text:
            print(f"{DOC.name} is stale — run: uv run python tools/generate_protocol_doc.py")
            return 1
        return 0
    DOC.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
