# Generated by tools/generate_types.py. Do not edit.
# Derived from examples/measurements/. Stale costs autocomplete, never correctness.
#
# A .pyi replaces its module for a type checker, so everything public in
# comeni_core.profile is declared here — not only the overloads that motivated it.
from typing import Literal, overload

from pydantic import BaseModel

from comeni_core.marks import ContractId, MeasurementId, ParamValue
from comeni_core.tiers import ValueSource

class Measured(BaseModel):
    measurement: MeasurementId
    value: ParamValue
    source: ValueSource
    by: ContractId | None

class DataProfile(BaseModel):
    measurements: list[Measured]
    @overload
    def get(self, measurement_id: Literal["n_samples"]) -> int | None: ...
    @overload
    def get(self, measurement_id: Literal["paired"]) -> bool | None: ...
    @overload
    def get(self, measurement_id: Literal["read_length"]) -> int | None: ...
    @overload
    def get(
        self, measurement_id: Literal["strandedness"]
    ) -> Literal["forward", "reverse", "unstranded"] | None: ...
    @overload
    def get(self, measurement_id: str) -> ParamValue: ...
